# -*- coding: utf-8 -*-
"""
tools/osm_geometry.py --only, tested without the network.

WHY THIS FILE EXISTS
    OpenStreetMap is edited continuously, so a full harvest moves every trace
    somebody has touched since the last one. PM-63 needed one row's Wikidata
    id corrected, and a full run four weeks on moved four other circuits'
    traces with it. --only refetches the named rows and keeps every other
    line of both harvest files byte for byte - which is a claim about bytes,
    so these tests compare bytes.

    python3 -m unittest discover -s tests
"""
import os
import tempfile
import unittest
from unittest import mock

from tools import osm_geometry as T

HEAD = ("# Generated by tools/osm_geometry.py on 2026-09-05. Do not edit by hand.\n"
        "# Source: OpenStreetMap via api.openstreetmap.org, ODbL 1.0. "
        "Relation ids from Wikidata (CC0).\n"
        "# Pit lane excluded by member role. Every row was measured and "
        "checked against the published length before it was written.\n"
        "# " + "|".join(T.GEOM_COLUMNS) + "\n")
KEPT = ('albert-park|current|Q171288|280443|5.3084|5.278|0.58|338|'
        '2025-03-10T23:17:16Z|{"type":"MultiLineString","coordinates":[[[1,2],[3,4]]]}')
OLD = ('long-beach||Q16739|18052024|3.2584|3.251|0.23|206|'
       '2024-09-16T16:57:01Z|{"type":"MultiLineString","coordinates":[[[5,6],[7,8]]]}')
KEPT_LOG = "albert-park\tACCEPTED\trelation 280443\t5.3084 km (+0.58%)"
OLD_LOG = "long-beach\tACCEPTED\trelation 18052024\t3.2584 km (+0.23%)"
GEO = {"type": "MultiLineString", "coordinates": [[[5, 6], [7, 8]]]}


class OnlyRefetchesWhatItNames(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.dir = self.tmp.name
        self.txt = os.path.join(self.dir, "circuit_geometry.txt")
        self.log = os.path.join(self.dir, "circuit_geometry.log")
        with open(self.txt, "w", encoding="utf-8") as f:
            f.write(HEAD + KEPT + "\n" + OLD + "\n")
        with open(self.log, "w", encoding="utf-8") as f:
            f.write("# Every admitted circuit, and why it was refused.\n"
                    + KEPT_LOG + "\n" + OLD_LOG + "\n")

    def tearDown(self):
        self.tmp.cleanup()

    def run_only(self, only, fetched):
        with mock.patch.object(T, "HARVEST", self.dir), \
             mock.patch.object(T, "relation_geometry", fetched) as fetch, \
             mock.patch("builtins.print"):
            T.harvest(only)
        return fetch

    def lines(self, path):
        with open(path, encoding="utf-8") as f:
            return f.read().splitlines()

    def test_the_named_row_is_refetched_and_the_rest_kept(self):
        fetch = self.run_only({"long-beach"},
                              mock.Mock(return_value=(GEO, 3258.4, 206, "2024-09-16T16:57:01Z")))
        fetch.assert_called_once_with(18052024)
        got = self.lines(self.txt)
        self.assertEqual(got[0], "# Generated by tools/osm_geometry.py on 2026-09-05; "
                                 "long-beach refetched on " + T.time.strftime("%Y-%m-%d")
                                 + ". Do not edit by hand.")
        self.assertEqual(got[1:4], HEAD.splitlines()[1:4])
        self.assertEqual(got[4], KEPT)
        from data.circuits import WIKIDATA_CIRCUITS
        self.assertEqual(got[5].split("|")[2], WIKIDATA_CIRCUITS["long-beach"][0])
        self.assertEqual(len(got), 6)
        self.assertEqual(self.lines(self.log)[1:], [KEPT_LOG, OLD_LOG])

    def test_a_rerun_the_same_day_states_its_clause_once(self):
        fetched = mock.Mock(return_value=(GEO, 3258.4, 206, "2024-09-16T16:57:01Z"))
        self.run_only({"long-beach"}, fetched)
        once = self.lines(self.txt)
        self.run_only({"long-beach"}, fetched)
        self.assertEqual(self.lines(self.txt), once)

    def test_a_file_with_no_header_is_refused_before_anything_is_written(self):
        with open(self.txt, "w", encoding="utf-8") as f:
            f.write(KEPT + "\n")
        with self.assertRaises(SystemExit):
            self.run_only({"long-beach"},
                          mock.Mock(return_value=(GEO, 3258.4, 206, "2024-09-16T16:57:01Z")))
        self.assertEqual(self.lines(self.txt), [KEPT])

    def test_a_refused_refetch_drops_its_row_and_logs_why(self):
        self.run_only({"long-beach"}, mock.Mock(return_value=(None, 0, 0, None)))
        self.assertEqual(self.lines(self.txt)[4:], [KEPT])
        log = self.lines(self.log)[1:]
        self.assertEqual(log[1], KEPT_LOG)
        self.assertTrue(log[0].startswith("long-beach\tREFUSED\t"), log[0])

    def test_an_unadmitted_circuit_is_refused_before_anything_is_fetched(self):
        fetch = mock.Mock()
        with self.assertRaises(SystemExit):
            self.run_only({"not-a-circuit"}, fetch)
        fetch.assert_not_called()
        self.assertEqual(self.lines(self.txt)[4:], [KEPT, OLD])


if __name__ == "__main__":
    unittest.main()
