"""refresh.yml's `report` job: is the data behind, and what the issues do (SD-35).

WHY THIS FILE EXISTS
    From 2026-10-02 every refresh failed for three days and nothing said so.
    The two halves of the fix fail quietly in opposite directions: a check
    that never finds a race late is the silence it was written to end, and
    one that alarms through a winter break, or for ever over a cancelled
    race, is an alarm people learn to ignore. So these tests are mostly
    about where the line falls.

WHY A DATABASE OF ITS OWN
    refresh.yml runs this suite as a gate on every refreshed harvest. A test
    that read the committed f1.db for "this race has no result yet" or "F1DB
    holds no calendar for next season" would fail the first refresh that
    brought the result or the calendar, and so every refresh after it - the
    outage this check exists to report, caused by its own tests (review
    finding on #805). So the rule is tested on a few rows written here, in
    seasons no harvest will reach, and the real files are only read to show
    they still parse.

    python3 -m unittest tests.test_refresh_health
"""
import datetime as dt
import importlib.util
import os
import sqlite3
import sys
import tempfile
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(ROOT, ".github", "scripts")
DB = os.path.join(ROOT, "f1.db")
CALENDAR = os.path.join(ROOT, "harvest", "race_dates.txt")


def load(name):
    spec = importlib.util.spec_from_file_location(name, os.path.join(SCRIPTS, f"{name}.py"))
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


health = load("refresh_health")
alarm = load("refresh_alarm")


def day(stamp):
    return dt.date.fromisoformat(stamp)


# 2030: F1DB's calendar holds the season. Round 1 has its result, rounds 2
# and 3 have none. 2031: F1DB holds nothing yet, as 2027 is today.
RACES = [
    (1, 2030, 1, "First Grand Prix", "2030-03-10"),
    (2, 2030, 2, "Second Grand Prix", "2030-03-17"),
    (3, 2030, 3, "Third Grand Prix", "2030-03-24"),
    (4, 2031, 1, "Next First Grand Prix", "2031-03-09"),
]
RESULTED = [1]
F1DB = [(2030, 1, "2030-03-10"), (2030, 2, "2030-03-17"), (2030, 3, "2030-03-24")]


class Fixture(unittest.TestCase):
    def setUp(self):
        self.dir = tempfile.TemporaryDirectory()
        self.db = os.path.join(self.dir.name, "f1.db")
        self.calendar_path = os.path.join(self.dir.name, "race_dates.txt")
        con = sqlite3.connect(self.db)
        con.executescript("""
            CREATE TABLE races (id INTEGER PRIMARY KEY, year INTEGER, round INTEGER,
                                name_used TEXT, date_iso TEXT);
            CREATE TABLE race_entries (id INTEGER PRIMARY KEY, race_id INTEGER);""")
        con.executemany("INSERT INTO races VALUES (?, ?, ?, ?, ?)", RACES)
        con.executemany("INSERT INTO race_entries (race_id) VALUES (?)", [(r,) for r in RESULTED])
        con.commit()
        con.close()
        with open(self.calendar_path, "w", encoding="utf-8") as f:
            f.write("# Generated by tools/f1db_fetch.py. Do not edit by hand.\n"
                    "# year|round|date\n")
            f.writelines(f"{y}|{r}|{d}\n" for y, r, d in F1DB)
        self.con = sqlite3.connect(f"file:{self.db}?mode=ro", uri=True)
        self.calendar = health.f1db_calendar(self.calendar_path)

    def tearDown(self):
        self.con.close()
        self.dir.cleanup()

    def late(self, stamp, calendar=None):
        late, unlisted = health.late_races(
            self.con, self.calendar if calendar is None else calendar, day(stamp))
        return [(r["year"], r["round"]) for r in late], [(r["year"], r["round"]) for r in unlisted]


class ARaceIsLateAfterThreeDays(Fixture):
    def test_not_on_the_third_day(self):
        self.assertEqual(self.late("2030-03-20"), ([], []))

    def test_on_the_fourth(self):
        self.assertEqual(self.late("2030-03-21"), ([(2030, 2)], []))

    def test_a_race_with_a_result_is_never_late(self):
        self.assertNotIn((2030, 1), self.late("2030-06-01")[0])

    def test_a_break_raises_nothing(self):
        # A week after round 1, which has its result, and before round 2: no
        # race date has passed unreported, so no time without a refresh says
        # anything - which is right, as there was nothing to report.
        self.assertEqual(self.late("2030-03-16"), ([], []))

    def test_a_round_f1db_has_dropped_is_not_late(self):
        # The same season, with F1DB's calendar no longer listing 17 March:
        # taken as cancelled or moved, said as a note, and never an alarm.
        dropped = self.calendar - {(2030, "2030-03-17")}
        self.assertEqual(self.late("2030-03-21", dropped), ([], [(2030, 2)]))

    def test_a_season_f1db_does_not_hold_counts_on_its_typed_dates(self):
        # Not a season of cancellations but one the harvest has not reached -
        # and a refresh that died over the winter would never reach it.
        self.assertIn((2031, 1), self.late("2031-03-13")[0])
        self.assertNotIn((2031, 1), self.late("2031-03-12")[0])


class ASeasonNeedsACalendarByFebruary(Fixture):
    def test_on_the_first_of_february(self):
        self.assertEqual(health.season_without_calendar(self.con, day("2032-02-01")), 2032)

    def test_not_on_the_last_of_january(self):
        self.assertIsNone(health.season_without_calendar(self.con, day("2032-01-31")))

    def test_not_for_a_season_that_has_one(self):
        self.assertIsNone(health.season_without_calendar(self.con, day("2031-02-01")))


class TheReport(Fixture):
    def test_a_problem_keeps_its_key_as_the_days_go_by(self):
        one, _ = health.check(self.db, self.calendar_path, day("2030-03-21"))
        two, _ = health.check(self.db, self.calendar_path, day("2030-03-22"))
        self.assertEqual([k for k, _ in one], ["2030/2"])
        self.assertEqual([k for k, _ in one], [k for k, _ in two])
        self.assertNotEqual(one[0][1], two[0][1])

    def test_it_names_the_race_and_the_day(self):
        problems, notes = health.check(self.db, self.calendar_path, day("2030-03-21"))
        text = health.report(problems, notes, day("2030-03-21"))
        self.assertIn("Second Grand Prix", text)
        self.assertIn("2030-03-17, 4 days ago", text)

    def test_a_missing_calendar_is_a_problem_with_its_own_key(self):
        problems, _ = health.check(self.db, self.calendar_path, day("2032-02-01"))
        self.assertIn("2032/calendar", [k for k, _ in problems])


class TheRealFilesStillParse(unittest.TestCase):
    """Only that they can be read: no fact in them is load-bearing here."""

    def test_the_harvest_calendar(self):
        self.assertIn((1950, "1950-05-13"), health.f1db_calendar(CALENDAR))

    def test_the_database(self):
        if not os.path.exists(DB):
            self.skipTest("f1.db has not been built")
        problems, notes = health.check(DB, CALENDAR, day("2026-10-05"))
        self.assertIsInstance(problems, list)
        self.assertIsInstance(notes, list)


class TheIssues(unittest.TestCase):
    def results(self, gate="success", refresh="success", land="success"):
        return dict(gate=gate, refresh=refresh, land=land)

    def test_a_failed_job_opens_one_and_then_only_updates_it(self):
        failed = self.results(refresh="failure", land="skipped")
        self.assertEqual(alarm.failure_action(failed, False), "open")
        self.assertEqual(alarm.failure_action(failed, True), "update")

    def test_a_gate_that_cannot_mint_a_token_is_a_failure(self):
        self.assertEqual(alarm.failure_action(
            self.results("failure", "skipped", "skipped"), False), "open")

    def test_a_timed_out_job_is_a_failure(self):
        self.assertEqual(alarm.failure_action(
            self.results(refresh="cancelled", land="skipped"), False), "open")

    def test_only_a_run_that_lands_closes_it(self):
        self.assertEqual(alarm.failure_action(self.results(), True), "close")
        self.assertIsNone(alarm.failure_action(self.results(), False))
        stopped = self.results(refresh="skipped", land="skipped")
        self.assertIsNone(alarm.failure_action(stopped, True))

    def test_freshness_follows_the_check(self):
        late = [("2026/16", "- late")]
        self.assertEqual(alarm.freshness_action(late, False), "open")
        self.assertEqual(alarm.freshness_action(late, True), "update")
        self.assertEqual(alarm.freshness_action([], True), "close")
        self.assertIsNone(alarm.freshness_action([], False))

    def test_the_state_survives_a_round_trip_through_the_body(self):
        state = dict(signature="`refresh`: Rebuild and verify", count=16, first="2026-10-02")
        body = alarm.with_mark(alarm.failure_body(["x"], "u", "w", 16, "2026-10-02"), state)
        self.assertEqual(alarm.read_mark(body), state)

    def test_a_brace_in_a_step_name_does_not_lose_the_state(self):
        state = dict(signature="`refresh`: Fetch {F1DB}", count=2, first="2026-10-02")
        self.assertEqual(alarm.read_mark(alarm.with_mark("body", state)), state)

    def test_a_body_without_state_reads_as_none(self):
        self.assertEqual(alarm.read_mark("edited by hand"), {})
        self.assertEqual(alarm.read_mark("<!-- refresh-alarm {broken -->"), {})
        self.assertEqual(alarm.read_mark(None), {})


if __name__ == "__main__":
    unittest.main()
