# -*- coding: utf-8 -*-
"""
Fetch the chassis, engine and per-season entrant register from F1DB.

    python3 tools/f1db_fetch.py                    # clone and regenerate
    python3 tools/f1db_fetch.py --source ~/f1db    # use an existing checkout
    python3 tools/f1db_fetch.py --check            # regenerate and diff only

Source:  https://github.com/f1db/f1db   (CC BY 4.0)
Writes:  harvest/chassis.txt, harvest/engines.txt, harvest/entrants.txt,
         harvest/entrant_drivers.txt, harvest/f1db_constructors.txt,
         harvest/f1db_drivers.txt

Why a tool and not a person
---------------------------
This is 1,153 chassis, 424 engines and 1,799 entrant rows. CONTRIBUTING.md is
explicit that data at that scale goes through a loader and never through a
human: during v2.7 an API harvest was relayed by hand and four of five sampled
rows came back fabricated. So this script fetches and writes; nobody types.

Why the output is a text file and not a direct write to f1.db
-------------------------------------------------------------
`build.py` is offline and reproducible, and CI rebuilds the database from
`data/` and `harvest/` on every push. A loader that wrote straight into f1.db
would put data in the distributed artefact that no fresh build could
reproduce. Writing diffable text instead keeps one rule intact - the database
is a function of the sources in this repository - and means a change in F1DB
shows up in a pull request as readable lines.

What F1DB does and does not give you
------------------------------------
The `chassis` entity is a complete register of every chassis that has raced:
id, constructorId, name, fullName. It carries **no technical specifications
at all** - no weight, no wheelbase, no suspension. Those come from the
per-car Wikipedia harvest (tools/wikispec_fetch.py) instead.

The `engine` entity does carry capacity, configuration and aspiration.

`seasons/<year>/entrants.yml` links season -> entrant -> constructor ->
chassis/engine/tyre. That mapping is the second source the chassis-per-race
harvest was missing (known_gaps #1). It has one hard limit, and it decides
how far the linkage can go:

    **F1DB records which chassis a constructor ran in a season. It does not
    record which chassis ran in which round.**

Where a team ran two designs in a year - Lotus in 1970, Ferrari in 1975 - the
entrant block lists both under a `chassis:` list with no round attribution.
So the mapping constrains the chassis only for constructor-seasons that used
exactly one. Those are stored; the rest stay NULL. Multi-chassis seasons are
written out too, with every chassis on the row, so the ambiguity is recorded
rather than dropped - build.py refuses to link them.
"""
import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
HARVEST = os.path.join(ROOT, "harvest")
CACHE = os.path.join(ROOT, ".f1dbcache")
REPO = "https://github.com/f1db/f1db.git"

HEADER = """\
# Generated by tools/f1db_fetch.py. Do not edit by hand.
# Source: F1DB {version} ({commit}), https://github.com/f1db/f1db, CC BY 4.0.
# {fields}
"""


def _yaml():
    try:
        import yaml
    except ImportError:
        sys.exit("PyYAML is needed by this tool (not by the build): "
                 "pip install pyyaml")
    return yaml


def checkout(source):
    """Return (path, version, commit) for an F1DB working tree."""
    if source:
        path = os.path.abspath(os.path.expanduser(source))
        if not os.path.isdir(os.path.join(path, "src", "data")):
            sys.exit(f"{path} does not look like an F1DB checkout")
    else:
        path = CACHE
        if os.path.isdir(os.path.join(path, ".git")):
            run(["git", "-C", path, "fetch", "--depth", "1", "origin", "HEAD"])
            run(["git", "-C", path, "reset", "--hard", "FETCH_HEAD"])
        else:
            run(["git", "clone", "--depth", "1", REPO, path])
    commit = run(["git", "-C", path, "rev-parse", "--short", "HEAD"]).strip()
    version = run(["git", "-C", path, "log", "-1", "--format=%s"]).strip()
    version = version.split(":")[-1].strip()
    return path, version, commit


def run(cmd):
    p = subprocess.run(cmd, capture_output=True, text=True)
    if p.returncode:
        sys.exit(f"{' '.join(cmd)} failed:\n{p.stderr}")
    return p.stdout


def _clean(value):
    """A field going into a pipe-delimited file may not contain a pipe or a
    newline. Nothing in F1DB does; fail loudly rather than corrupt a row."""
    if value is None:
        return ""
    s = str(value).strip()
    if "|" in s or "\n" in s:
        sys.exit(f"field contains a delimiter and cannot be stored: {s!r}")
    return s


def _listify(entry, single, plural, key):
    """F1DB writes one value as `chassisId: x` and several as a `chassis:`
    list of `- chassisId: x`. Return both shapes as a list, in file order."""
    out = []
    if entry.get(single):
        out.append(entry[single])
    for item in entry.get(plural) or []:
        if item.get(key):
            out.append(item[key])
    seen, uniq = set(), []
    for v in out:
        if v not in seen:
            seen.add(v)
            uniq.append(v)
    return uniq


def write(name, header_fields, rows, version, commit, check):
    path = os.path.join(HARVEST, name)
    body = HEADER.format(version=version, commit=commit, fields=header_fields)
    body += "".join(r + "\n" for r in rows)
    if check:
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        state = "unchanged" if old == body else "CHANGED"
        print(f"  {name:16s} {len(rows):5d} rows  {state}")
        return old == body
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"  {name:16s} {len(rows):5d} rows written")
    return True


def chassis_rows(data, yaml):
    import glob
    rows = []
    for p in sorted(glob.glob(os.path.join(data, "chassis", "*.yml"))):
        d = yaml.safe_load(open(p, encoding="utf-8"))
        rows.append("|".join(_clean(d.get(k)) for k in
                             ("id", "constructorId", "name", "fullName")))
    return sorted(rows)


def engine_rows(data, yaml):
    import glob
    rows = []
    for p in sorted(glob.glob(os.path.join(data, "engines", "*.yml"))):
        d = yaml.safe_load(open(p, encoding="utf-8"))
        rows.append("|".join(_clean(d.get(k)) for k in
                             ("id", "engineManufacturerId", "name", "fullName",
                              "capacity", "configuration", "aspiration")))
    return sorted(rows)


def constructor_rows(data, yaml):
    """The constructor names, so the Wikipedia spec harvest can check an
    article's stated constructor against the one F1DB gives the chassis
    without a second network fetch."""
    import glob
    rows = []
    for p in sorted(glob.glob(os.path.join(data, "constructors", "*.yml"))):
        d = yaml.safe_load(open(p, encoding="utf-8"))
        rows.append("|".join(_clean(d.get(k)) for k in
                             ("id", "name", "fullName", "countryId")))
    return sorted(rows)


def country_rows(data, yaml):
    """Country ids to their names, so a constructor's country can be written
    the way this register writes it rather than title-cased from a slug.
    `united-states-of-america` is not "United States Of America"."""
    import glob
    rows = []
    for p in sorted(glob.glob(os.path.join(data, "countries", "*.yml"))):
        d = yaml.safe_load(open(p, encoding="utf-8"))
        rows.append("|".join(_clean(d.get(k)) for k in
                             ("id", "name", "alpha3Code", "demonym")))
    return sorted(rows)


def driver_rows(data, yaml):
    """The driver register: enough to resolve a race entry to an F1DB driver
    offline, and enough to describe one the register admits.

    This file never decides that a driver exists - data/drivers.py does that,
    one authored line at a time. It only supplies the spelling, the dates and
    the nationality for the ones already admitted."""
    import glob
    rows = []
    for p in sorted(glob.glob(os.path.join(data, "drivers", "*.yml"))):
        d = yaml.safe_load(open(p, encoding="utf-8"))
        rows.append("|".join(_clean(d.get(k)) for k in
                             ("id", "name", "firstName", "lastName",
                              "dateOfBirth", "dateOfDeath", "abbreviation",
                              "nationalityCountryId")))
    return sorted(rows)


def entrant_driver_rows(data, yaml):
    """One row per (season, entrant, constructor, engine manufacturer, driver).

    `rounds` is copied verbatim - "1-10", "1,4-5", "3" - and parsed in
    data/harvest.py, not here, so the file records exactly what the source
    says. A driver with no rounds is a test driver who did not enter a race;
    those rows are written with an empty rounds field and the build ignores
    them rather than assuming they raced everything."""
    import glob
    rows = []
    for p in sorted(glob.glob(os.path.join(data, "seasons", "*", "entrants.yml"))):
        year = int(os.path.basename(os.path.dirname(p)))
        for entrant in yaml.safe_load(open(p, encoding="utf-8")) or []:
            eid = entrant["entrantId"]
            for b in (entrant.get("constructors") or [entrant]):
                if not b.get("constructorId"):
                    continue
                drivers = b.get("drivers")
                if drivers is None and b.get("driverId"):
                    drivers = [{"driverId": b["driverId"],
                                "rounds": b.get("rounds")}]
                for d in drivers or []:
                    if not d.get("driverId"):
                        continue
                    rows.append("|".join([
                        str(year), _clean(eid), _clean(b["constructorId"]),
                        _clean(b.get("engineManufacturerId")),
                        _clean(d["driverId"]), _clean(d.get("rounds")),
                        "1" if d.get("testDriver") else "0",
                    ]))
    return rows


def entrant_rows(data, yaml):
    """One row per (year, entrant, constructor, engine manufacturer).

    The engine manufacturer is part of the grain, not decoration. Team Lotus
    in 1966 is one entrant with two constructor blocks, both `lotus`, one on
    Climax and one on BRM - a Lotus 33 and a Lotus 43. Collapsing them would
    merge two different cars into one row.

    Chassis, engines and tyres are '+'-joined where the source lists several,
    because the source does not say which went with which. Flattening them
    into separate rows would invent a pairing F1DB never claimed."""
    import glob
    rows = []
    for p in sorted(glob.glob(os.path.join(data, "seasons", "*", "entrants.yml"))):
        year = int(os.path.basename(os.path.dirname(p)))
        for entrant in yaml.safe_load(open(p, encoding="utf-8")) or []:
            eid = entrant["entrantId"]
            # An entrant can field cars from more than one constructor in a
            # season (Andy Granatelli, 1952: a Bromme and a Kurtis Kraft).
            blocks = entrant.get("constructors") or [entrant]
            for b in blocks:
                if not b.get("constructorId"):
                    continue
                rows.append("|".join([
                    str(year), _clean(eid), _clean(b["constructorId"]),
                    _clean(b.get("engineManufacturerId")),
                    "+".join(_clean(v) for v in
                             _listify(b, "chassisId", "chassis", "chassisId")),
                    "+".join(_clean(v) for v in
                             _listify(b, "engineId", "engines", "engineId")),
                    "+".join(_clean(v) for v in
                             _listify(b, "tyreManufacturerId",
                                      "tyreManufacturers", "tyreManufacturerId")),
                ]))
    return rows


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--source", help="an existing F1DB checkout to read instead "
                                     "of cloning")
    ap.add_argument("--check", action="store_true",
                    help="regenerate in memory and report whether the committed "
                         "files still match; write nothing")
    args = ap.parse_args()

    yaml = _yaml()
    path, version, commit = checkout(args.source)
    data = os.path.join(path, "src", "data")
    print(f"F1DB {version} ({commit}) from {path}")

    ok = True
    ok &= write("chassis.txt", "chassis_id|constructor_id|name|full_name",
                chassis_rows(data, yaml), version, commit, args.check)
    ok &= write("engines.txt",
                "engine_id|manufacturer_id|name|full_name|capacity_l|"
                "configuration|aspiration",
                engine_rows(data, yaml), version, commit, args.check)
    ok &= write("f1db_constructors.txt",
                "constructor_id|name|full_name|country_id",
                constructor_rows(data, yaml), version, commit, args.check)
    ok &= write("f1db_countries.txt",
                "country_id|name|alpha3|demonym",
                country_rows(data, yaml), version, commit, args.check)
    ok &= write("f1db_drivers.txt",
                "driver_id|name|first_name|last_name|date_of_birth|"
                "date_of_death|abbreviation|nationality_country_id",
                driver_rows(data, yaml), version, commit, args.check)
    ok &= write("entrants.txt",
                "year|entrant_id|constructor_id|engine_manufacturer_id|"
                "chassis_ids|engine_ids|tyre_ids"
                "   ('+' separates values the source does not disambiguate)",
                entrant_rows(data, yaml), version, commit, args.check)
    ok &= write("entrant_drivers.txt",
                "year|entrant_id|constructor_id|engine_manufacturer_id|"
                "driver_id|rounds|test_driver"
                "   (rounds is verbatim: '1-10', '1,4-5'; empty = did not race)",
                entrant_driver_rows(data, yaml), version, commit, args.check)
    if args.check and not ok:
        sys.exit("the committed harvest files are out of date with F1DB")


if __name__ == "__main__":
    main()
